### PR TITLE
Output

### PR DESCRIPTION
**Pull request by YagmurSimsekk**

### CODE REVIEW

**Comment by YagmurSimsekk** [comment]
Hi,

I have changed the function outputs from list to TreeSE object for all simulations. However, the problem is there were different types of features in the list object which I didn't know where to insert when converting to TreeSE format. I probably would need @gaoyu19920914 help on what exactly the outputs features were in the list object and @antagomir help to figure out where to insert these features in TreeSE. Also, the GitHub actions doesn't really even run through the file, it throws an error immediately. Maybe @TuomasBorman help me to look into that. 

I am planning to change the documentation and examples after the TreeSE object correctly implemented in the functions.

**Comment by gaoyu19920914** [comment]
Hello,

The output features in each simulations contains basically 3 parts:

1. a matrix of species dynamics along the time (with columns as species and last column as time), and
2. (for CRM only) a matrix of resources dynamics (with columns as resources and last column as time) and a matrix of volume dynamics (with first column as volume and last column as time), and
3. other useful data for each simulation, generally some important inputs. This is designed to keep the data provenance and simplify the chaining of different simulations. Their meanings and types can be found in the documentation of each `simulateXXX` function. You can also refer to [this link](https://docs.google.com/spreadsheets/d/13oBu5IJD9MKwhwRIU5_wMdCjtAC6jIeiqDq8xxJ-MVQ/edit?usp=sharing) for more details.

**Comment by antagomir** [comment]
1. goes to assay data; the time column is different type and it should go to `colData` where it actually belongs since it is sample / colData, not assay data; functions to be updated accordingly
2. goes to colData; note that these columns would be better called by their _name_ in functions rather than location in order to reduce possibility for errors and allow extensibility
3. goes to metadata (`metadata(tse) <- list(...)` so just add all the extra stuff there as a list); this slot is inherited from the _SingleCellExperiment_ class.

OK?

**Comment by antagomir** [comment]
Re: build error in GHA.

You changed from master to main branch? Then the github actions (GHA) workflow file should be updated accordingly for automated tests (master -> main): `.github/workflows/*.yml`. Perhaps this solves the issue or at least some of it.

**Comment by YagmurSimsekk** [comment]
> 

There was no master branch previously, it was initially set to main, actually. I also thought changing it in the `.github/workflows/*.yml` would work, but it doesn't recognize the main branch as well.

**Comment by YagmurSimsekk** [comment]
Examples, tests and vignette are corrected, convertToSE function is removed. Only there are some functions in utils file that could be useful such as `generateSimulations` since it generates multiple simulations out of one simulation function and stores them in a list. Same can be done with TreeSE object (multiple TreeSE objects in a list) but it can also be removed.

**Comment by antagomir** [comment]
Me / Tuomas can check those final list and other things once this is otherwise completed. Kindly confirm when this seems ready from your side? We may then still suggest some updates (or possibly not).

**Comment by TuomasBorman** [comment]
mia had same problem with GHA, I fixed it in this PR https://github.com/microbiome/mia/pull/323

**Comment by YagmurSimsekk** [comment]
It is ready from my side. Feel free to check and give your feedback/suggest changes.

**Comment by antagomir** [comment]
Do @danielriosgarza or @gaoyu19920914 have anything coming up before we check the next round with @TuomasBorman ?

**Comment by danielriosgarza** [comment]
> Do @danielriosgarza or @gaoyu19920914 have anything coming up before we check the next round with @TuomasBorman ?

Not from my side

**Comment by gaoyu19920914** [comment]
> Do @danielriosgarza or @gaoyu19920914 have anything coming up before we check the next round with @TuomasBorman ?

Nothing from me. Good to go

**Comment by antagomir** [comment]
Great! 

@TuomasBorman could you review the package for us. I will then have a final look if something more is needed.

**Comment by YagmurSimsekk** [comment]
The website actually shows what is on main branch. After the changes in this PR merged, the website should change as well. For now, whatever is in the vignette of the main branch is also on the website. 

Also, the checks are failing because of the `generateSimulations` function in utils. This can be handled by either removing the function or just changing its structure to TreeSE and the output of the function still can remain list object.

**Comment by antagomir** [comment]
Clear, great.

Do I understand correctly that `generateSimulations` is generating a list of TreeSE objects, each corresponding to a different set of parameters? I am not sure how necessary the other arguments are after the first two - `model` and `params_list`. It seems those other arguments that are listed after these can be incorporated through `params_list` as well, and that would be more direct and clear way.

If so, then a more straightforward way to run the same is something like:

.. for varying parameters (given as a list):

`simlist <- lapply(params_list, function (pars) { do.call(model, pars) })`

.. and for `n_instances` plus fixed parameters (`pars`):

`simlist <- lapply(seq_len(n_instances), function (i) { do.call(model, pars) })`

This is simple and clear, and it could be shown in examples and vignettes.

That would save us from maintenance burden for this function that is relatively complicated, and seems to have parameter options that tend to override each other in somewhat complicated ways.

Hence I suggest to remove this function and replace it with examples showing how to do the same with `lapply`.

This will imply changes in other parts of utils.R and perhaps in unit tests and vignettes (to be checked).

@YagmurSimsekk could you implement the change? Then the error should be solved.

**Comment by YagmurSimsekk** [comment]
There is only one more function left to clear: `estimateAFromSimulations` in utils.R. Is it necessary to keep this function and implement with TreeSE object? Or could it be also written with some built-in functions and shown in vignette?

**Comment by YagmurSimsekk** [comment]
This function uses parameter `simulations`  which is a list object that would be created by `generateSimulations` function that is just removed. So the parameters and the most of the function has to be changed accordingly if the function is staying. Before changing anything, I would like to hear from @gaoyu19920914 and @danielriosgarza if this function is essential and can be shown with some examples using TreeSE.

**Comment by gaoyu19920914** [comment]
> This function uses parameter `simulations` which is a list object that would be created by `generateSimulations` function that is just removed. So the parameters and the most of the function has to be changed accordingly if the function is staying. Before changing anything, I would like to hear from @gaoyu19920914 and @danielriosgarza if this function is essential and can be shown with some examples using TreeSE.

Hello and sorry for the late reply.

This `estimateAFromSimulations`function is written to show how different models could be connected. This is one of main reasons why we bring various models together and keep them in the same data structure.

It is useful to estimate the matrix A (as in the gLV model) from different kinds of simulations, and one example is given in `utils.R` in the devel branch: estimate matrix A from CRM-based simulations, and then simulate another time-series using gLV model with this estimated A.

With this function and the example, people can see how these models could interact, and understand why the unified data format (either the previous matrix or current TreeSE) is used.

**Comment by antagomir** [comment]
Great, then it is good to keep. 

It would be good to merge the current branches as soon as possible, then we could check this one based on the final main branch and make sure that the examples run well.

**Comment by antagomir** [comment]
This is almost passing the checks: Error: package or namespace load failed for ‘miaSim’ in namespaceExport(ns, exports):
 undefined exports: generateSimulations, getCommunity -> @YagmurSimsekk could you have a look?

I open a separate issue about `estimateAFromSimulations`

**Comment by YagmurSimsekk** [comment]
Thanks! @antagomir

**Pull request merged**
