### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by YagmurSimsekk**
We have kept the latest version of the package in the devel branch. We can merge the devel branch into the main branch to make https://microbiome.github.io/miaSim/ look more accurate, and we can also update the package in the Bioconductor environment if you agree @antagomir

### CODE REVIEW

**Comment by YagmurSimsekk** [comment]
R cmd fails because of the installation of Bioc package(miaTime), it is the same error that occurred before. Otherwise, devtools::check() doesn't throw any error or warnings.

**Comment by antagomir** [comment]
1. Check if miaTime as dependency can be removed?
2. If not, check if it can be moved to Suggests in DESCRIPTION file and add this in .github/workflows scripts: Rscript -e "remotes::install_github('r-hub/sysreqs')"

**Review by YagmurSimsekk — COMMENTED** [review]
I have tried to add the line in these sections, but it didn't work.

**Comment by antagomir** [comment]
also remove miaTime from GHA

**Comment by YagmurSimsekk** [comment]
@antagomir PR is ready to merge right now

**Pull request merged**
