### PR TITLE
Maintainer should be listed first

### PR DESCRIPTION
**Pull request by antagomir**
Testing automated website generation,.

### CODE REVIEW

**Comment by antagomir** [comment]
I cannot merge this before review by someone (@YagmurSimsekk ?)

**Comment by YagmurSimsekk** [comment]
Sorry, i will change the settings now, and you will be able to merge without review again

**Comment by antagomir** [comment]
I wanted to use this to test if automated builds are activating with the PR.. now this was merged before I could see if that happened.. :-)

**Comment by antagomir** [comment]
However one thing we can see is that the automated website build, that should activate after the merge, is not active:

**Comment by antagomir** [comment]
This brings us back to issue #36

**Pull request merged**
