### PR TITLE
unify classes and defaults in params definition

### PR DESCRIPTION
**Pull request by 0xMuluh**
This PR harmonizes the definition of parameters to be in conformity with the miaverse standards.

### CODE REVIEW

**Comment by 0xMuluh** [comment]
Good to go

**Comment by 0xMuluh** [comment]
Can we merge this one? @antagomir

**Review by TuomasBorman — APPROVED** [review]

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Btw. might be good to wait next release

@YagmurSimsekk

**Comment by antagomir** [comment]
I guess it is ok. We can merge after the Oct release if this is better.

**Comment by YagmurSimsekk** [comment]
Changes after 15 October are not included in the new release. So it is good to go.

**Comment by antagomir** [comment]
Great!

**Pull request merged**
